FROM golang:1.12 AS build

WORKDIR $GOPATH/src/github.com/Harrison-Miller/kagstats

ADD go.mod .
ADD go.sum .
ADD vendor/ ./vendor

ADD common/ ./common
ADD collector/ ./collector

WORKDIR $GOPATH/src/github.com/Harrison-Miller/kagstats/collector

RUN GO111MODULE=on GOARCH=386 CGO_ENABLED=0 GOOS=linux go build -o collector -mod=vendor ./...

RUN cp collector / && cp -r templates / && cp -r scripts /

FROM alpine

ARG VERSION
ENV VERSION=$VERSION

ADD LICENSE .

COPY --from=build /collector /

RUN mkdir -p /templates /scripts
COPY --from=build /templates/ /templates
COPY --from=build /scripts/ /scripts

ENV MONITOR_HOST=":8081"
ENV DB="root:password@tcp(mysql:3306)/kagstats?charset=utf8mb4"
ENV KAGSTATS_CONFIG="settings.json"

EXPOSE 8081

CMD ["/collector"]
