FROM golang:1.12 AS build

WORKDIR $GOPATH/src/github.com/Harrison-Miller/kagstats

ADD . .

WORKDIR $GOPATH/src/github.com/Harrison-Miller/kagstats/api

RUN go get -d -v ./...

RUN GOARCH=386 CGO_ENABLED=0 GOOS=linux go build -o api -i -v ./...

RUN cp api /

FROM scratch

COPY --from=build /api /

CMD ["/api"]
