version: "3.7"
services:
  mysql:
    build:
      context: .
      dockerfile: Dockerfile-mysql
    image: gcr.io/kagstats/mysql:${TAG:-latest}
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=kagstats
    restart: always
  collector:
    build:
      context: .
      dockerfile: Dockerfile-collector
    image: gcr.io/kagstats/collector:${TAG:-latest}
    ports:
      - "8081:8081"
    links:
      - mysql
    restart: always
    volumes:
      - ${SETTINGS:-./settings.json}:/settings.json
  api:
    build:
      context: .
      dockerfile: Dockerfile-api
    image: gcr.io/kagstats/api:${TAG:-latest}
    ports:
      - "8080:8080"
    links:
      - mysql
    hostname: api
    restart: always
  basic-indexer:
    build:
      context: .
      dockerfile: Dockerfile-indexer
      args:
        indexer: basic
    image: gcr.io/kagstats/basic-indexer:${TAG:-latest}
    environment:
      - INDEXER_INTERVAL=10s
    links:
      - mysql
    restart: always
  nemesis-indexer:
    build:
      context: .
      dockerfile: Dockerfile-indexer
      args:
        indexer: nemesis
    image: gcr.io/kagstats/nemesis-indexer:${TAG:-latest}
    environment:
      - INDEXER_INTERVAL=10s
    links:
      - mysql
    restart: always
  hitters-indexer:
    build:
      context: .
      dockerfile: Dockerfile-indexer
      args:
        indexer: hitters
    image: gcr.io/kagstats/hitters-indexer:${TAG:-latest}
    environment:
      - INDEXER_INTERVAL=10s
    links:
      - mysql
    restart: always
  ui:
    build:
      context: .
      dockerfile: Dockerfile-ui
    image: gcr.io/kagstats/ui:${TAG:-latest}
    ports:
      - "80:80"
    links:
      - api
    restart: always