version: "3.7"
volumes:
  kagstats-data:
services:
  mysql:
    build:
      context: .
      dockerfile: Dockerfile-mysql
    image: gcr.io/kagstats/mysql:${TAG:-latest}
    volumes:
      - kagstats-data:/var/lib/mysql
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=kagstats
    command: ["mysqld", "--innodb_autoinc_lock_mode=0"]
    restart: always
  collector:
    build:
      context: .
      dockerfile: Dockerfile-collector
      args:
        VERSION: ${TAG:-latest}
    image: gcr.io/kagstats/collector:${TAG:-latest}
    links:
      - mysql
    restart: always
    volumes:
      - ${SETTINGS:-./settings.json}:/settings.json
  api:
    build:
      context: .
      dockerfile: Dockerfile-api
      args:
        VERSION: ${TAG:-latest}
    image: gcr.io/kagstats/api:${TAG:-latest}
    environment:
      - KD_GATE=25
      - ARCHER_GATE=15
      - BUILDER_GATE=5
      - KNIGHT_GATE=25
    links:
      - mysql
    hostname: api
    restart: always
  admin:
    build:
      context: .
      dockerfile: Dockerfile-admin
      args:
        VERSION: ${TAG:-latest}
    image: gcr.io/kagstats/admin:${TAG:-latest}
    environment:
      - USER=${ADMIN_USER:-admin}
      - PASS=${ADMIN_PASS:-admin1234!}
    links:
      - mysql
    hostname: admin
    restart: always
  basic-indexer:
    build:
      context: .
      dockerfile: Dockerfile-indexer
      args:
        indexer: basic
        VERSION: ${TAG:-latest}
    image: gcr.io/kagstats/basic-indexer:${TAG:-latest}
    links:
      - mysql
    restart: always
  nemesis-indexer:
    build:
      context: .
      dockerfile: Dockerfile-indexer
      args:
        indexer: nemesis
        VERSION: ${TAG:-latest}
    image: gcr.io/kagstats/nemesis-indexer:${TAG:-latest}
    links:
      - mysql
    restart: always
  hitters-indexer:
    build:
      context: .
      dockerfile: Dockerfile-indexer
      args:
        indexer: hitters
        VERSION: ${TAG:-latest}
    image: gcr.io/kagstats/hitters-indexer:${TAG:-latest}
    links:
      - mysql
    restart: always
  monthly-indexer:
    build:
      context: .
      dockerfile: Dockerfile-indexer
      args:
        indexer: monthly
        VERSION: ${TAG:-latest}
    image: gcr.io/kagstats/hitters-indexer:${TAG:-latest}
    links:
      - mysql
    restart: always
  apicache:
    build:
      context: .
      dockerfile: Dockerfile-indexer
      args:
        indexer: apicache
        VERSION: ${TAG:-latest}
    image: gcr.io/kagstats/apicache:${TAG:-latest}
    environment:
      - INDEXER_INTERVAL=20m
    links:
      - mysql
    restart: always
  accolades:
    build:
      context: .
      dockerfile: Dockerfile-indexer
      args:
        indexer: accolades
        VERSION: ${TAG:-latest}
    image: gcr.io/kagstats/accolades:${TAG:-latest}
    links:
      - mysql
    restart: always
  ui:
    build:
      context: .
      dockerfile: Dockerfile-ui
      args:
        VERSION: ${TAG:-latest}
    image: gcr.io/kagstats/ui:${TAG:-latest}
    ports:
      - "${WEB_PORT:-80}:80"
    links:
      - api
    restart: always