FROM node:latest

COPY ui /ui
WORKDIR /ui
RUN npm install
RUN npm run build --prod


FROM nginx:latest

RUN rm /etc/nginx/conf.d/default.conf

COPY ui/kagstats.conf /etc/nginx/conf.d
COPY ui/build /var/www/html
