version: "3.7"
services:
  mysql:
    build:
      context: .
      dockerfile: Dockerfile-mysql
    image: gcr.io/kagstats/mysql:${TAG:-latest}
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=kagstats
  api:
    build:
      context: .
      dockerfile: Dockerfile-api
    image: gcr.io/kagstats/api:${TAG:-latest}
    ports:
      - "8080:8080"
    links:
      - mysql
  basic-indexer:
    build:
      context: .
      dockerfile: Dockerfile-indexer
      args:
        indexer: basic
    image: gcr.io/kagstats/basic-indexer:${TAG:-latest}
    environment:
      - INDEXER_INTERVAL=10s
    links:
      - mysql
  nemesis-indexer:
    build:
      context: .
      dockerfile: Dockerfile-indexer
      args:
        indexer: nemesis
    image: gcr.io/kagstats/nemesis-indexer:${TAG:-latest}
    environment:
      - INDEXER_INTERVAL=10s
    links:
      - mysql
  hitters-indexer:
    build:
      context: .
      dockerfile: Dockerfile-indexer
      args:
        indexer: hitters
    image: gcr.io/kagstats/hitters-indexer:${TAG:-latest}
    environment:
      - INDEXER_INTERVAL=10s
    links:
      - mysql
