FROM golang:1.12 AS build

WORKDIR $GOPATH/src/github.com/Harrison-Miller/kagstats

ADD go.mod .
ADD go.sum .
ADD vendor/ ./vendor

ADD common/ ./common
ADD indexer/ ./indexer

ARG indexer=basic

WORKDIR $GOPATH/src/github.com/Harrison-Miller/kagstats/indexer/${indexer}

RUN GO111MODULE=on GOARCH=386 CGO_ENABLED=0 GOOS=linux go build -o indexer -mod=vendor ./...

RUN cp indexer /

FROM alpine AS certs

RUN apk update && apk add --no-cache ca-certificates && update-ca-certificates

FROM scratch

ARG VERSION
ENV VERSION=$VERSION

COPY --from=certs /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

ADD LICENSE .

COPY --from=build /indexer /

ENV INDEXER_DB="root:password@tcp(mysql:3306)/kagstats?charset=utf8mb4"
ENV INDEXER_BATCHSIZE="100"
ENV INDEXER_INTERVAL="30s"

CMD ["/indexer"]
