FROM golang:1.12 AS build

WORKDIR $GOPATH/src/github.com/Harrison-Miller/kagstats

ADD go.mod .
ADD go.sum .
ADD vendor/ ./vendor

ADD common/ ./common
ADD api/ ./api

WORKDIR $GOPATH/src/github.com/Harrison-Miller/kagstats/api

RUN GO111MODULE=on GOARCH=386 CGO_ENABLED=0 GOOS=linux go build -o api -mod=vendor ./...

RUN cp api /

FROM alpine AS certs

RUN apk update && apk add --no-cache ca-certificates && update-ca-certificates

FROM scratch

ARG VERSION
ENV VERSION=$VERSION

COPY --from=certs /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

ADD LICENSE .

COPY --from=build /api /

ENV API_HOST=":8080"
ENV API_DB="root:password@tcp(mysql:3306)/kagstats?charset=utf8mb4"

EXPOSE 8080

CMD ["/api"]
