FROM golang:1.12 AS build

WORKDIR $GOPATH/src/github.com/Harrison-Miller/kagstats

ADD go.mod .
ADD go.sum .
ADD vendor/ ./vendor

ADD common/ ./common
ADD indexer/ ./indexer

ARG indexer=basic

WORKDIR $GOPATH/src/github.com/Harrison-Miller/kagstats/indexer/${indexer}

RUN GO111MODULE=on GOARCH=386 CGO_ENABLED=0 GOOS=linux go build -o indexer -mod=vendor ./...

RUN cp indexer /

FROM scratch

ADD LICENSE .

COPY --from=build /indexer /

ENV INDEXER_DB="root:password@tcp(mysql:3306)/kagstats"
ENV INDEXER_BATCHSIZE="100"
ENV INDEXER_INTERVAL="30s"

CMD ["/indexer"]
