FROM golang:1.12 AS build

WORKDIR $GOPATH/src/github.com/Harrison-Miller/kagstats

ADD . .

WORKDIR $GOPATH/src/github.com/Harrison-Miller/kagstats/api

RUN go get -d -v ./...

RUN GOARCH=386 CGO_ENABLED=0 GOOS=linux go build -o api -i -v ./...

RUN cp api /

FROM scratch

COPY --from=build /api /

ENV API_HOST=":8080"
ENV API_DB="root:password@tcp(mysql:3306)/kagstats"

EXPOSE 8080

CMD ["/api"]
