# mysql port 3306
# web port 81
version: "3.7"
services:
  mysql:
    image: mysql:5.7
  kag-propagate-bans:
    image: Harrison-Miller/kag-propagate-bans:latest
    restart: always
    volumes:
      - ${BANS_SETTINGS:-./index.json}:/kag-propagate-bans/index.json
  api:
    environment:
      - KD_GATE=75
      - ARCHER_GATE=40
      - BUILDER_GATE=20
      - KNIGHT_GATE=75
      - NEMESIS_GATE=11
  basic-indexer:
    environment:
      - INDEXER_BATCHSIZE=10000
  nemesis-indexer:
    environment:
      - INDEXER_BATCHSIZE=10000
  hitters-indexer:
    environment:
      - INDEXER_BATCHSIZE=10000
  monthly-hitters-indexer:
    environment:
      - INDEXER_BATCHSIZE=10000
  monthly-indexer:
    environment:
      - INDEXER_BATCHSIZE=10000