# mysql port 3306
# web port 81
version: "3.7"
services:
  mysql:
    image: mysql:5.7
  api:
    environment:
      - KD_GATE=75
      - ARCHER_GATE=40
      - BUILDER_GATE=20
      - KNIGHT_GATE=75
  basic-indexer:
    environment:
      - INDEXER_BATCHSIZE=3000
  nemesis-indexer:
    environment:
      - INDEXER_BATCHSIZE=1000
  hitters-indexer:
    environemtn:
      - INDEXER_BATCHSIZE=1000