steps:
- name: "gcr.io/cloud-builders/gcloud"
  entrypoint: "bash"
  args:
    - "-c"
    - |
      if [[ "$BRANCH_NAME" != "master" ]]; then
        echo "Not running staging pipeline on none master branch: $BRANCH_NAME"
        exit 1
      fi

- name: "docker/compose:1.24.0"
  args:
    - "build"
    - "--parallel"

- name: "docker/compose:1.24.0"
  args:
    - "push"

# TODO: do database backup of release and load it into staging

- name: "gcr.io/cloud-builders/gcloud"
  entrypoint: "bash"
  args:
    - "-c"
    - |
      echo "Starting deployment"
      gcloud compute ssh cloudbuild@staging --zone=us-central1-a --strict-host-key-checking=no -- -T << EOF
      y


      EOF
      gcloud compute ssh cloudbuild@staging --zone=us-central1-a --strict-host-key-checking=no -- -T << EOF
      sudo rm -rf /staging
      sudo mkdir -p /staging
      sudo chown cloudbuild /staging
      cd /staging
      curl https://raw.githubusercontent.com/Harrison-Miller/kagstats/master/docker-compose.yaml --output docker-compose.yaml
      curl https://raw.githubusercontent.com/Harrison-Miller/kagstats/master/builds/staging-compose.yaml --output staging-compose.yaml
      sudo docker-compose -p staging down --remove-orphans
      sudo docker-compose -f docker-compose.yaml -f staging-compose.yaml pull
      sudo SETTINGS=/settings.json docker-compose -f docker-compose.yaml -f staging-compose.yaml -p staging up -d
      EOF
      echo "Deployment finsihed"